name: Test
on:
  push
permissions:
  contents: read
jobs:
  build-and-test:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute shell commands before build
        run: |
          echo "Server datetime: $(date)"

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Build and Test
        run: |
          npm clean-install
          npm run build
          npm run test